INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (1, N'Register', N'Đăng ký')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (1, N'Hello {0}!', N'Chào {0}!')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (1, N'Log in', N'Đăng nhập')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (1, N'Log off', N'Đăng xuất')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (1, N'The Email field is required.', N'Địa chỉ email cần phải có ')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (1, N'Email', N'Địa chỉ email')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (1, N'User List', N'Danh sách người dùng')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (1, N'Remember me?', N'Ghi nhớ?')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (1, N'Password', N'Mật khẩu')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (1, N'Use a local account to log in.', N'Sử dụng tài khoản của bạn để đăng nhập')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (1, N'Register as a new user?', N'Đăng ký người dùng mới')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (1, N'Forgot your password?', N'Quên mật khẩu')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (1, N'Use another service to log in.', N'Đăng nhập bằng các tài khoản khác')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (1, N'Full name', N'Họ và tên')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (1, N'Confirm password', N'Xác nhận mật khẩu')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (1, N'Create a new account.', N'Tạo tài khoản mới.')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (1, N'All', N'Tất cả')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (1, N'Home', N'Trang chủ')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (1, N'Add to cart', N'Thêm vào giỏ hàng')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (1, N'Product detail', N'Mô tả sản phẩm')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (1, N'Product specification', N'Thông số kỹ thuật')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (1, N'Rate this product', N'Đánh giá sản phẩm này')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (1, N'Review comment', N'Mô tả đánh giá')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (1, N'Review title', N'Tiêu đề đánh giá')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (1, N'Posted by', N'Đánh giá bởi')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (1, N'Submit review', N'Gửi đánh giá')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (1, N'You have', N'Bạn có')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (1, N'products in your cart', N'sản phẩm trong giỏ hàng')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (1, N'Continue shopping', N'Tiếp tục mua sắm')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (1, N'View cart', N'Xem giỏ hàng')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (1, N'The product has been added to your cart', N'Sản phẩm đã được thêm vào giỏ hàng')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (1, N'Cart subtotal', N'Thành tiền')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (1, N'Shopping Cart', N'Giỏ hàng')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (1, N'Product', N'Sản phẩm')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (1, N'Price', N'Giá')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (1, N'Quantity', N'Số lượng')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (1, N'There are no items in this cart.', N'Chưa có sản phẩm nào trong giỏ hàng của bạn')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (1, N'Go to shopping', N'Đi mua sắm')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (1, N'Order summary', N'Tóm lược đơn hàng')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (1, N'Subtotal', N'Thành tiền')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (1, N'Process to Checkout', N'Tiến hành thanh toán')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (1, N'Shipping address', N'Địa chỉ giao hàng')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (1, N'Add another address', N'Thêm địa chỉ mới')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (1, N'Contact name', N'Tên người liên hệ')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (1, N'Address', N'Địa chỉ')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (1, N'State or Province', N'Thành phố / Tỉnh')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (1, N'District', N'Quận / Huyện')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (1, N'Phone', N'Số điện thoại')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (1, N'Order', N'Đặt hàng')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (1, N'products', N'sản phẩm')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (1, N'reviews', N'nhận xét')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (1, N'Add Review', N'Viết nhận xét')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (1, N'Customer reviews', N'Nhận xét của khách hàng')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (1, N'Your review will be showed within the next 24h.', N'Nhận xét của bạn sẽ được hiển thị trong vòng 24 tiếng')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (1, N'Thank you {0} for your review', N'Cảm ơn {0} đã gửi nhận xét')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (1, N'Rating average', N'Đánh giá trung bình')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (1, N'stars', N'sao')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (1, N'Filter by', N'Tìm theo')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (1, N'Category', N'Danh mục')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (1, N'Brand', N'Nhãn hiệu')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (1, N'Sort by:', N'Sắp xếp theo:')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (1, N'results', N'kết quả')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (1, N'View options', N'Xem các tùy chọn')

INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (2, N'Register', N'S''inscrire')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (2, N'Hello {0}!', N'Bonjour {0}!')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (2, N'Log in', N'Connexion')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (2, N'Log off', N'Déconnexion')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (2, N'The Email field is required.', N'Le champs Email est obligatoire.')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (2, N'Email', N'Email')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (2, N'User List', N'Liste des utilisateurs')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (2, N'Remember me?', N'Se rappeler de moi?');
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (2, N'Password', N'Mot de passe');
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (2, N'Use a local account to log in.', N'Utilisez un compte local pour vous connecter.');
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (2, N'Register as a new user?', N'Enregistrez-vous en tant que nouvel utilisateur?');
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (2, N'Forgot your password?', N'Mot de passe oublié?');
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (2, N'Use another service to log in.', N'Utilisez un autre service pour vous connecter.');
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (2, N'Full name', N'Nom complet');
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (2, N'Confirm password', N'Confirmez le mot de passe');
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (2, N'Create a new account.', N'Créer un nouveau compte.');
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (2, N'All', N'Tout');
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (2, N'Home', N'Accueil');
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (2, N'Add to cart', N'Ajouter au panier');
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (2, N'Product detail', N'Détail du produit');
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (2, N'Product specification', N'Spécification de produit');
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (2, N'Rate this product', N'Évaluez ce produit');
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (2, N'Review comment', N'Revue commentaire');
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (2, N'Review title', N'Revue titre');
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (2, N'Posted by', N'Posté par');
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (2, N'Submit review', N'Poster le commentaire');
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (2, N'You have', N'Vous avez');
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (2, N'products in your cart', N'produits dans votre panier');
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (2, N'Continue shopping', N'Continuer vos achats');
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (2, N'View cart', N'Voir le panier');
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (2, N'The product has been added to your cart', N'Le produit a été ajouté à votre panier');
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (2, N'Cart subtotal', N'Sous-total du panier');
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (2, N'Shopping Cart', N'Panier');
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (2, N'Product', N'Produit');
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (2, N'Price', N'Prix');
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (2, N'Quantity', N'Quantité');
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (2, N'There are no items in this cart.', N'Il n''y a aucun article dans votre panier.');
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (2, N'Go to shopping', N'Aller faire du shopping');
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (2, N'Order summary', N'Récapitulatif de la commande');
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (2, N'Subtotal', N'Sous-Total');
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (2, N'Process to Checkout', N'Processus de paiement');
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (2, N'Shipping address', N'Adresse de livraison');
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (2, N'Add another address', N'Ajouter une autre adresse');
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (2, N'Contact name', N'Nom du contactệ');
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (2, N'Address', N'Adresse');
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (2, N'State or Province', N'Etat ou Province');
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (2, N'District', N'District');
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (2, N'Phone', N'Téléphone');
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (2, N'Order', N'Commande');
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (2, N'products', N'Produits');
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (2, N'reviews', N'avis');
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (2, N'Add Review', N'Ajouter un commentaire');
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (2, N'Customer reviews', N'Avis des clients');
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (2, N'Your review will be showed within the next 24h.', N'Votre avis sera affiché dans les prochaines 24h.');
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (2, N'Thank you {0} for your review', N'Merci {0} pour votre commentaire');
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (2, N'Rating average', N'Moyenne des notes');
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (2, N'stars', N'étoiles');
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (2, N'Filter by', N'Filtrer par');
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (2, N'Category', N'Catalogue');
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (2, N'Brand', N'Marque');
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (2, N'Sort by:', N'Trier par:');
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (2, N'results', N'résultats');
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (2, N'View options', N'Afficher les options')

INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (3, N'Register', N'Cadastro')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (3, N'Hello {0}!', N'Olá {0}!')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (3, N'Log in', N'Entrar')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (3, N'Log off', N'Sair')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (3, N'The Email field is required.', N'O campo Email é obrigatório. ')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (3, N'Email', N'Email')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (3, N'User List', N'Lista de usuários')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (3, N'Remember me?', N'Lembrar?')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (3, N'Password', N'Senha')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (3, N'Use a local account to log in.', N'Entre com seu usuário e senha ')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (3, N'Register as a new user?', N'Cadastrar-se como novo usuário? ')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (3, N'Forgot your password?', N'Esqueceu a senha?')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (3, N'Use another service to log in.', N'Logar utilizando outro serviço')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (3, N'Full name', N'Nome completo')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (3, N'Confirm password', N'Confirmar senha')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (3, N'Create a new account.', N'Criar uma conta.')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (3, N'All', N'Todos')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (3, N'Home', N'Início')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (3, N'Add to cart', N'Adicionar ao carrinho')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (3, N'Product detail', N'Detalhes do produto')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (3, N'Product specification', N'Especificações do produto')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (3, N'Rate this product', N'Avalie este produto')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (3, N'Review comment', N'Comentário')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (3, N'Review title', N'Título da avaliação')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (3, N'Posted by', N'Postado pro')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (3, N'Submit review', N'Enviar avaliação')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (3, N'You have', N'Você tem')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (3, N'products in your cart', N'produtos no carrinho')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (3, N'Continue shopping', N'Continuar comprando')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (3, N'View cart', N'Ver carrinho')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (3, N'The product has been added to your cart', N'O produto foi adicionado ao carrinho')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (3, N'Cart subtotal', N'Subtotal')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (3, N'Shopping Cart', N'Carrinho de compras')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (3, N'Product', N'Produto')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (3, N'Price', N'Preço')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (3, N'Quantity', N'Quantidade')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (3, N'There are no items in this cart.', N'O carrinho está vazio.')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (3, N'Go to shopping', N'a comprar')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (3, N'Order summary', N'Resumo do pedido')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (3, N'Subtotal', N'Subtotal')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (3, N'Process to Checkout', N'Próxima etapa')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (3, N'Shipping address', N'Endereço de entrega')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (3, N'Add another address', N'Adicionar outro endereço')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (3, N'Contact name', N'Nome completo')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (3, N'Address', N'Endereço')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (3, N'State or Province', N'Estado')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (3, N'District', N'Cidade')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (3, N'Phone', N'Telefone')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (3, N'Order', N'Pedido')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (3, N'products', N'produtos')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (3, N'reviews', N'avaliações')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (3, N'Add Review', N'Adicionar avaliação')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (3, N'Customer reviews', N'Avaliações de quem comprou')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (3, N'Your review will be showed within the next 24h.', N'Sua avaliação será publicada dentro de 24h.')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (3, N'Thank you {0} for your review', N'Muito obrigado pela avaliação, {0}')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (3, N'Rating average', N'Média das avaliações')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (3, N'stars', N'estrelas')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (3, N'Filter by', N'Filtrar por')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (3, N'Category', N'Categoria')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (3, N'Brand', N'Marca')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (3, N'Sort by:', N'Ordenar por:')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (3, N'results', N'resultados')

INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (4, N'Register', N'Зареєструватися')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (4, N'Hello {0}!', N'Вітаємо, {0}!')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (4, N'Log in', N'Увійти')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (4, N'Log off', N'Вийти')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (4, N'The Email field is required.', N'Поле «Електронна пошта» є обов’язковим.')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (4, N'Email', N'Електронна пошта')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (4, N'User List', N'Список користувачів')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (4, N'Remember me?', N'Запам’ятати мене?')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (4, N'Password', N'Пароль')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (4, N'Use a local account to log in.', N'Використати локальний акаунт для входу.')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (4, N'Register as a new user?', N'Зареєструватися як новий користувач?')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (4, N'Forgot your password?', N'Забули свій пароль?')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (4, N'Use another service to log in.', N'Використати інший сервіс для входу.')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (4, N'Full name', N'Повне ім’я')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (4, N'Confirm password', N'Підтвердження паролю')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (4, N'Create a new account.', N'Створити новий акаунт.')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (4, N'All', N'Всі')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (4, N'Home', N'Головна')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (4, N'Add to cart', N'Додати до кошику')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (4, N'Product detail', N'Деталі товару')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (4, N'Product specification', N'Специфікація товару')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (4, N'Rate this product', N'Оцінити цей продукт')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (4, N'Review comment', N'Текст відгуку')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (4, N'Review title', N'Заголовок відгуку')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (4, N'Posted by', N'Автор')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (4, N'Submit review', N'Надіслати відгук')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (4, N'You have', N'Ви маєте')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (4, N'products in your cart', N'товарів у кошику')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (4, N'Continue shopping', N'Tiếp tục mua sắm')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (4, N'View cart', N'Переглянути кошик')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (4, N'The product has been added to your cart', N'Товар було додано до кошику')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (4, N'Cart subtotal', N'Проміжний підсумок')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (4, N'Shopping Cart', N'Кошик')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (4, N'Product', N'Товар')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (4, N'Price', N'Ціна')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (4, N'Quantity', N'Кількість')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (4, N'There are no items in this cart.', N'Товарів у кошику немає')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (4, N'Go to shopping', N'Продовжити покупки')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (4, N'Order summary', N'Підсумок замовлення')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (4, N'Subtotal', N'Підсумок')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (4, N'Process to Checkout', N'Оформити замовлення')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (4, N'Shipping address', N'Адреса доставки')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (4, N'Add another address', N'Додати іншу адресу')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (4, N'Contact name', N'Контактне ім’я ')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (4, N'Address', N'Адреса')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (4, N'State or Province', N'Область або край')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (4, N'District', N'Район')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (4, N'Phone', N'Телефон')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (4, N'Order', N'Замовлення')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (4, N'products', N'товари')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (4, N'reviews', N'відгуки')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (4, N'Add Review', N'Додати відгук')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (4, N'Customer reviews', N'Відгуки покупців')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (4, N'Your review will be showed within the next 24h.', N'Ваш відгук буде опубліковано впродовж наступних 24 годин.')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (4, N'Thank you {0} for your review', N'Дякуємо {0} за ваш відгук')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (4, N'Rating average', N'Середня оцінка')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (4, N'stars', N'зірочок')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (4, N'Filter by', N'Фільтрувати за')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (4, N'Category', N'Категорія')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (4, N'Brand', N'Бренд')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (4, N'Sort by:', N'Сортувати за:')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (4, N'results', N'результати')

INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (5, N'Register', N'Зарегистрироваться')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (5, N'Hello {0}!', N'Поздравляем, {0}!')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (5, N'Log in', N'Войти')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (5, N'Log off', N'Выйти')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (5, N'The Email field is required.', N'Поле «Электронная почта» является обязательным.')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (5, N'Email', N'Электронная почта')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (5, N'User List', N'Список пользователей')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (5, N'Remember me?', N'Запомнить меня?')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (5, N'Password', N'Пароль')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (5, N'Use a local account to log in.', N'Использовать локальный аккаунт для входа.')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (5, N'Register as a new user?', N'Зарегистрироваться как новый пользователь?')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (5, N'Forgot your password?', N'Забыли свой пароль?')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (5, N'Use another service to log in.', N'Использовать другой сервис для входа.')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (5, N'Full name', N'Полное имя')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (5, N'Confirm password', N'Подтверждение пароля')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (5, N'Create a new account.', N'Создать новый аккаунт.')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (5, N'All', N'Все')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (5, N'Home', N'Главная')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (5, N'Add to cart', N'Добавить в корзину')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (5, N'Product detail', N'Детали товара')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (5, N'Product specification', N'Спецификация товара')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (5, N'Rate this product', N'Оценить этот товар')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (5, N'Review comment', N'Текст отзыва')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (5, N'Review title', N'Заголовок отзыва')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (5, N'Posted by', N'Автор')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (5, N'Submit review', N'Отправить отзыв')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (5, N'You have', N'У вас')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (5, N'products in your cart', N'товаров в корзине')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (5, N'Continue shopping', N'Продолжить покупки')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (5, N'View cart', N'Просмотр корзины')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (5, N'The product has been added to your cart', N'Товар был добавлен в корзину')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (5, N'Cart subtotal', N'Промежуточный итог')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (5, N'Shopping Cart', N'Корзина')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (5, N'Product', N'Товар')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (5, N'Price', N'Цена')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (5, N'Quantity', N'Количество')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (5, N'There are no items in this cart.', N'Товаров в корзине нет')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (5, N'Go to shopping', N'Продолжить покупки')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (5, N'Order summary', N'Итог заказа')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (5, N'Subtotal', N'Итого')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (5, N'Process to Checkout', N'Оформить заказ')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (5, N'Shipping address', N'Адрес доставки')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (5, N'Add another address', N'Добавить другой адрес')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (5, N'Contact name', N'Контактное имя')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (5, N'Address', N'Адрес')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (5, N'State or Province', N'Область или край')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (5, N'District', N'Район')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (5, N'Phone', N'Телефон')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (5, N'Order', N'Заказ')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (5, N'products', N'товары')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (5, N'reviews', N'отзывы')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (5, N'Add Review', N'Добавить отзыв')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (5, N'Customer reviews', N'Отзывы покупателей')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (5, N'Your review will be showed within the next 24h.', N'Ваш отзыв будет опубликован в течении следующих 24 часов.')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (5, N'Thank you {0} for your review', N'Спасибо {0} за ваш отзыв')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (5, N'Rating average', N'Средняя оценка')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (5, N'stars', N'звездочек')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (5, N'Filter by', N'Фильтровать по')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (5, N'Category', N'Категория')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (5, N'Brand', N'Бренд')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (5, N'Sort by:', N'Сортировать по:')
INSERT [dbo].[ResourceDbContext] ([CultureId], [Key], [Value]) VALUES (5, N'results', N'результаты')